### PR TITLE
Adds scrolling functionality to comment pane (pgup pgdn). Adds date to comment 

### PR DESCRIPTION
**Pull request by stoicism2323**
To-do: change readme (is pgup/pgdn ok?)
Add link pane functionality.
Ensure time is accurate

### CODE REVIEW

**Comment by Cotix** [comment]
I like most of what you have written, but I have a few comments:

- In your string/char litterals you use ASCII, and pass this into wide char functions. For example:
`wchar_t *foundNewLineString = wcschr(currentTextPointer, '\n');`

   Should be:

   `wchar_t *foundNewLineString = wcschr(currentTextPointer, L'\n');`
- You added the variable that keeps track of the scrolling in reddit.h. I'm not sure if I like this. I'd rather have it in the screen structures, since it has to do with the screen. 
- I think line 284 is wrong.

  `unsigned int distanceToNewLine = foundNewLineString - currentTextPointer + 1;`

  FoundNewLineString and currentTextPointer are pointers to a wchar, so every char is sizeof(wchar_t) long. (on my machine 4 bytes) You compare this with the width, which is the amount of characters, so if the newline is within 1/4th of the screen width it works, but if it is only 1/2th of the width it should jump to the newline, but now instead it jumps the whole width, which might result in a jump of 2 lines. This should be fixed (i think) by dividing the distance by sizeof(wchar_t)
- Your scroll up seems overcomplicated. You copy everything above the screen to a buffer (which you forget to free --> memory leak upon scrolling up) and than search for the last newline in that buffer. What I would recommend doing is using just wcschr to find the first occurence on the original text, but call it in a while loop untill you get a pointer that is either NULL or after the current scroll point. Then take the last new line you found before that point, and use that. This way you dont have to copy buffers around, and the code will look a lot more like the scroll down code, which is nice and makes things more understandable.
- I like the pageup/pagedown change. But please change the readme and help functions in the same pullrequest that you change the controls in. 



I hope you don't feel too discouraged, I like it that there is some activity again. I just prefer having good pull requests instead of pulling something with issues and than fixing these later on. Once these issues are fixed, I'll gladly merge it, since it is actually quite an important feature..

**Comment by DSMan195276** [comment]
I've been following this pull request. I concur with everything Cotix said, but wanted to add a few things:

 - 
Line 284 is fine. When you subtract pointers, the difference is given in units in the size of the object it's pointing too. It's a bit strange, but it works the same way adding pointers does. IE. If you do:

   ```
    int *i;
    i++;
   ```

   That advances `i` to the next *int*, which actually technically adds 4 to the underlying pointer (`sizeof(int)` generally is 4). We never have to think in this way though, because `i` is always in units based on the size of the `int`.

   Subtracting is the same way, just a bit stranger. The returned value is in units based on the size of the object you were pointing to. So if you subtract 1 from `i`, then it points to the `int` directly before the one is was originally pointing too.

   When you subtract to pointers, it returns the difference, but still in the same units. Really it's just an extension of the above. `(i + 1) - i` *has* to equal `1`, or else you'd have bigger problems. The only way for that to work is if subtracting pointers keeps the same rules as adding and subtracting them does, and thus the unit is still the size of the object being pointed too.

 - I also agree the scrolling is a bit too complicated, but I think it's a pretty simple fix. The buffer is used to be able to use the `wcsrchr` function when scrolling up, but you really don't need that function. I think you'd be better off writing your own `wcschr` function that searches *backwards*. That way it can just search for the first occurrence before the currently displayed text, and you can give it a length to stop at. Writing that function is fairly simple (`wcschr` is nothing more then a `for` loop), and the result should be much cleaner.

   It would be good to avoid searching through the entirely of the comment text when it's not necessary - scrolling up or down should only require looking at a max of 'screen width' number of characters. Lots of uses of `wcslen` and `wcschr` (Which search the entire string) could be replaced with `wcsnlen` and `wcsnchr`, because you know that if these functions return a value larger then the current screen width you're just going to ignore the result anyway (IE. If the screen width is 40, then it's pointless to look more then 40 characters away for a newline. After 40, you don't care if you find one because you're just going to scroll a screen-width anyway).

   Using those functions and passing them the screen width should both clean-up the code logic (Some of the special cases will go away) and make the functions run in a constant amount of time, where the length of the comment has no barring on how long scrolling takes (Which is how it should be).

**Comment by Cotix** [comment]
Hmm, I see, I did not know substracting pointers did that.

Initially I suggested a for loop too, but after thinking about it, it would be nicer to make use of functions like wcschr because writing your own functions for widechars might be slightly more tricky than that. But I agree that in this case, searching back is the way to go.

**Comment by DSMan195276** [comment]
Note: I had a typo in the last comment. There is no `wcsnchr` function, it's called `wmemchr`, But note that `wmemchr` does not stop on a NUL character, so you should take the length first using `wcsnlen` and then use that length.

The real crime is that there's no 'search backwards' functions at all, when they're fairly trivial to write and could have been added with no real downside. If you look at musl's widechar functions they're what you'd [expect](http://fossies.org/dox/musl-1.0.5/wcschr_8c_source.html), nothing surprising. The function needed here is something like this:

```
wchar_t *reverse_wcsnchr(wchar_t *start, size_t len, wchar_t c)
{
    wchar_t *end = start - len;

    for (; start != end && *start != c; start--)
        ;

    return (start != end)? start: NULL;
}
```

The only confusing pat is whether or not `start` points to the beginning or the end of the area to search. In this case, I treated it as though it points at the end. To me, that makes more sense since if the length wasn't included it would have to point at the end, so it's more consistent with how the other functions go. Also note, technically we can't name it `wcsnchr_reverse`, because all functions starting with `wcs` are reserved by the standard, which is why I put `reverse` first.

**Comment by stoicism2323** [comment]
Thanks for the extensive feedback cotix and dsman! I kind of assumed that github pull requests are for like 'hey look at this code diff', but if there's a better function to use in github for that i'd like to know. :) (Can you add a diff to a regular issue?). 

I'll update the commit if I can figure out how to apply those suggestions :) 

Thanks

**Comment by stoicism2323** [comment]
I guess we can close this pull request, further comments i've put in issue #69

**Pull request closed without merging**
