### PR TITLE
Adds scrolling to text in links/comments pane. Adds date to link and comment. Rebuild screen after closing opened link

### PR DESCRIPTION
**Pull request by stoicism2323**
The 'rebuild screen after closing opened link' part only is a step in the right direction it seems. The part I'm referring to is the added lines after the "case 'o'" in showSubreddit(). It's okay to not merge that part if you dont want it.

Thanks!

### CODE REVIEW

**Comment by stoicism2323** [comment]
darnit, forgot to commit one more change

**Comment by Cotix** [comment]
Is there a specific reason why advance is still in the link or command structures, and not in the screen structures? Except for that, the code looks good.

**Comment by stoicism2323** [comment]
Thanks for the feedback Cotix. I figured that if its in the link and comment structs, then you can:

1 Open any comment in the comment screen
2 scroll down on the text
3 go to some other comment, then go back to the comment in step 1
4 this comment will still be scrolled to where you left it

I believe if the advance variable is in LinkScreen and CommentScreen instead of RedditLink and RedditComment, then when you scroll back to the original comment it'll be scrolled back up to the top. I prefer it remembering the scroll point per comment, but it would save lots of space if it's in LinkScreen and CommentScreen so if you want it to be changed that makes sense :).

**Comment by Cotix** [comment]
I guess that makes sense. I'll merge this then.

**Pull request merged**
